### ISSUE TITLE
Комментарий 

### ISSUE THREAD

**Issue by BSUIRstudent** [Eugenito/TuningHUB#2]
Идея проекта хорошая. Удобно, когда есть, где можно подобрать детали к своему автомобилю.  
Проблема в том, что сам проект просится выйти как не desktop приложение, а как сайт. Хотелось бы просто перейти по ссылке и подобрать детали, а не устанавливать для этого приложение. Интерфейс как раз-таки подходит под это.

**Comment by Eugenito** [comment]
Спасибо вам за комментарий.Обосную свой выбор: Идея в том,чтобы не пришлось заходить на сайт ,а вы могли просто открыть приложение на своем компьютере и без надобности заходить в браузер быстро подобрать запчасть.
